export const OFFER_ADD_SUCCESS='OFFER_ADD_SUCCESS'
export const OFFER_FETCH_SUCCESS='OFFER_FETCH_SUCCESS'
export const OFFER_FETCH_ERROR='OFFER_FETCH_ERROR'
export const OFFER_FETCH_REQUEST='OFFER_FETCH_REQUEST'

export const COUPEN_ADD_SUCCESS='COUPEN_ADD_SUCCESS'
export const COUPEN_FETCH_SUCCESS='COUPEN_FETCH_SUCCESS'
export const COUPEN_FETCH_ERROR='COUPEN_FETCH_ERROR'
export const COUPEN_FETCH_REQUEST='COUPEN_FETCH_REQUEST'