export const STORE_ADDRESS = 'STORE_ADDRES'
export const STORE_AMOUNT = 'STORE_CART_AMOUNT'
export const STORE_CART_ITEMS='STORE_CART_ITEMS'
export const PAYMENT_METHOD='PAYMENT_METHOD'

export const GET_ADDRESS = 'STORE_ADDRES'
export const GET_AMOUNT = 'STORE_CART_AMOUNT'
export const GET_CART_ITEMS='STORE_CART_ITEMS'

