export const USER_FETCH_REQUEST='USER_FETCH_REQUEST'
export const USER_FETCH_SUCCESS='USER_FETCH_SUCCESS'
export const USER_FETCH_ERROR='USER_FETCH_ERROR'
export const USER_FETCH_VERIFY='USER_FETCH_VERIFY'