export const ORDER_ADD_SUCCESS='ORDER_ADD_SUCCESS'
export const ORDER_FETCH_SUCCESS='ORDER_FETCH_SUCCESS'
export const ORDER_FETCH_ERROR='ORDER_FETCH_ERROR'
export const ORDER_FETCH_REQUEST='ORDER_FETCH_REQUEST'

export const ORDER_PAY_REQUEST='ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS='ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL='ORDER_PAY_FAIL'
export const ORDER_PAY_RESET='ORDER_PAY_RESET'



