export const ORDER_ADD_SUCCESS='ORDER_ADD_SUCCESS'
export const ORDER_FETCH_SUCCESS='ORDER_FETCH_SUCCESS'
export const ORDER_FETCH_ERROR='ORDER_FETCH_ERROR'
export const ORDER_FETCH_REQUEST='ORDER_FETCH_REQUEST'